################################################################################
##
##  AUTHOR      Kevin Matthes
##  BRIEF       The definition of a GitHub Action.
##  COPYRIGHT   (C) 2022 Kevin Matthes.
##              This file is licensed MIT.
##  DATE        2022
##  FILE        cffconvert.yml
##  NOTE        See `LICENSE' for full license.
##              See `README.md' for project details.
##
################################################################################

name: cffconvert

on:
  push:
    paths:
      - CITATION.cff

permissions:
  contents: read

jobs:
  validation:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false

      - name: cffconvert
        uses: citation-file-format/cffconvert-github-action@4cf11baa70a673bfdf9dad0acc7ee33b3f4b6084
        with:
          args: "--validate"

################################################################################
