name: mirror

on:
  push:
    branches:
      - main
    paths:
      - src/lib.rs

permissions:
  contents: write

jobs:
  readme:
    name: readme
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.4.0

      - name: user
        uses: fregante/setup-git-user@v2.0.1

      - name: aeruginous
        run: |
          rustup update \
          && cargo install aeruginous \
          && aeruginous rs2md -i src/lib.rs -o README.md --outer \
          && git add README.md \
          && git commit --allow-empty -m \
                 "`git config --list \
                   | grep user\.name \
                   | cut -d= -f2`: Mirror README.md from src/lib.rs" \
          && git push
